// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCode  string                 `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Money) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type StockItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductId        string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	WarehouseId      string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	QuantityOnHand   int32                  `protobuf:"varint,3,opt,name=quantity_on_hand,json=quantityOnHand,proto3" json:"quantity_on_hand,omitempty"`
	QuantityReserved int32                  `protobuf:"varint,4,opt,name=quantity_reserved,json=quantityReserved,proto3" json:"quantity_reserved,omitempty"`
	UnitPrice        *Money                 `protobuf:"bytes,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StockItem) Reset() {
	*x = StockItem{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockItem) ProtoMessage() {}

func (x *StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockItem.ProtoReflect.Descriptor instead.
func (*StockItem) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *StockItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockItem) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *StockItem) GetQuantityOnHand() int32 {
	if x != nil {
		return x.QuantityOnHand
	}
	return 0
}

func (x *StockItem) GetQuantityReserved() int32 {
	if x != nil {
		return x.QuantityReserved
	}
	return 0
}

func (x *StockItem) GetUnitPrice() *Money {
	if x != nil {
		return x.UnitPrice
	}
	return nil
}

type GetStockItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockItemRequest) Reset() {
	*x = GetStockItemRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockItemRequest) ProtoMessage() {}

func (x *GetStockItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockItemRequest.ProtoReflect.Descriptor instead.
func (*GetStockItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetStockItemRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetStockItemRequest) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

type GetStockItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *StockItem             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockItemResponse) Reset() {
	*x = GetStockItemResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockItemResponse) ProtoMessage() {}

func (x *GetStockItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockItemResponse.ProtoReflect.Descriptor instead.
func (*GetStockItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetStockItemResponse) GetItem() *StockItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type BatchGetStockItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []string               `protobuf:"bytes,1,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetStockItemsRequest) Reset() {
	*x = BatchGetStockItemsRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetStockItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetStockItemsRequest) ProtoMessage() {}

func (x *BatchGetStockItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetStockItemsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetStockItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetStockItemsRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *BatchGetStockItemsRequest) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

type BatchGetStockItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StockItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetStockItemsResponse) Reset() {
	*x = BatchGetStockItemsResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetStockItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetStockItemsResponse) ProtoMessage() {}

func (x *BatchGetStockItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetStockItemsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetStockItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetStockItemsResponse) GetItems() []*StockItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\"proto/inventory/v1/inventory.proto\x12\x16supermart.inventory.v1\"D\n" +
	"\x05Money\x12#\n" +
	"\rcurrency_code\x18\x01 \x01(\tR\fcurrencyCode\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"\x87\x02\n" +
	"\tStockItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12(\n" +
	"\x10quantity_on_hand\x18\x03 \x01(\x05R\x0equantityOnHand\x12+\n" +
	"\x11quantity_reserved\x18\x04 \x01(\x05R\x10quantityReserved\x12<\n" +
	"\n" +
	"unit_price\x18\x05 \x01(\v2\x1d.supermart.inventory.v1.MoneyR\tunitPriceJ\x04\b\x06\x10\aJ\x04\b\a\x10\bR\n" +
	"legacy_skuR\vdescription\"W\n" +
	"\x13GetStockItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\"M\n" +
	"\x14GetStockItemResponse\x125\n" +
	"\x04item\x18\x01 \x01(\v2!.supermart.inventory.v1.StockItemR\x04item\"_\n" +
	"\x19BatchGetStockItemsRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\tR\n" +
	"productIds\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\"U\n" +
	"\x1aBatchGetStockItemsResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.supermart.inventory.v1.StockItemR\x05items2\xfa\x01\n" +
	"\x10InventoryService\x12i\n" +
	"\fGetStockItem\x12+.supermart.inventory.v1.GetStockItemRequest\x1a,.supermart.inventory.v1.GetStockItemResponse\x12{\n" +
	"\x12BatchGetStockItems\x121.supermart.inventory.v1.BatchGetStockItemsRequest\x1a2.supermart.inventory.v1.BatchGetStockItemsResponseBXZVgithub.com/tomprasetya/microservices-supermart-kelompok/proto/inventory/v1;inventoryv1b\x06proto3"

var (
	file_proto_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_v1_inventory_proto_rawDescData []byte
)

func file_proto_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_v1_inventory_proto_rawDesc), len(file_proto_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_v1_inventory_proto_rawDescData
}

var file_proto_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_inventory_v1_inventory_proto_goTypes = []any{
	(*Money)(nil),                      // 0: supermart.inventory.v1.Money
	(*StockItem)(nil),                  // 1: supermart.inventory.v1.StockItem
	(*GetStockItemRequest)(nil),        // 2: supermart.inventory.v1.GetStockItemRequest
	(*GetStockItemResponse)(nil),       // 3: supermart.inventory.v1.GetStockItemResponse
	(*BatchGetStockItemsRequest)(nil),  // 4: supermart.inventory.v1.BatchGetStockItemsRequest
	(*BatchGetStockItemsResponse)(nil), // 5: supermart.inventory.v1.BatchGetStockItemsResponse
}
var file_proto_inventory_v1_inventory_proto_depIdxs = []int32{
	0, // 0: supermart.inventory.v1.StockItem.unit_price:type_name -> supermart.inventory.v1.Money
	1, // 1: supermart.inventory.v1.GetStockItemResponse.item:type_name -> supermart.inventory.v1.StockItem
	1, // 2: supermart.inventory.v1.BatchGetStockItemsResponse.items:type_name -> supermart.inventory.v1.StockItem
	2, // 3: supermart.inventory.v1.InventoryService.GetStockItem:input_type -> supermart.inventory.v1.GetStockItemRequest
	4, // 4: supermart.inventory.v1.InventoryService.BatchGetStockItems:input_type -> supermart.inventory.v1.BatchGetStockItemsRequest
	3, // 5: supermart.inventory.v1.InventoryService.GetStockItem:output_type -> supermart.inventory.v1.GetStockItemResponse
	5, // 6: supermart.inventory.v1.InventoryService.BatchGetStockItems:output_type -> supermart.inventory.v1.BatchGetStockItemsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_inventory_v1_inventory_proto_init() }
func file_proto_inventory_v1_inventory_proto_init() {
	if File_proto_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_v1_inventory_proto_rawDesc), len(file_proto_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_v1_inventory_proto = out.File
	file_proto_inventory_v1_inventory_proto_goTypes = nil
	file_proto_inventory_v1_inventory_proto_depIdxs = nil
}
