syntax = "proto3";

package supermart.inventory.v1;

option go_package = "github.com/tomprasetya/microservices-supermart-kelompok/proto/inventory/v1;inventoryv1";

service InventoryService {
  rpc GetStockItem (GetStockItemRequest) returns (GetStockItemResponse);
  rpc BatchGetStockItems (BatchGetStockItemsRequest) returns (BatchGetStockItemsResponse);
}

message Money {
  string currency_code = 1;
  int64 amount = 2;
}

message StockItem {
  string product_id = 1;
  string warehouse_id = 2;
  int32 quantity_on_hand = 3;
  int32 quantity_reserved = 4;
  Money unit_price = 5;

  reserved 6, 7;
  reserved "legacy_sku", "description";
}

message GetStockItemRequest {
  string product_id = 1;
  string warehouse_id = 2;
}

message GetStockItemResponse {
  StockItem item = 1;
}

message BatchGetStockItemsRequest {
  repeated string product_ids = 1;
  string warehouse_id = 2;
}

message BatchGetStockItemsResponse {
  repeated StockItem items = 1;
}